apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maah
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/maah-slack-app
  newTag: 99df935115ff112654ffbc9686cdefca50b134f5
