apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maah
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/maah-slack-app
  newTag: 9eb3e20f8b0ac044f09ed2546bde7adc56457f31
